#!/usr/bin/env python3
"""encrypt-strings.py — dex 层字符串常量加密(构建期异或 + 运行期 Java 解密桩)

【这是什么】
把「用户选中类」里 dex 的字符串常量(const-string 字面量)在构建期加密,
运行期由注入的纯 Java 解密桩解密。目标是让 `strings`/静态特征扫描看不到
源码里写死的明文(URL/API key/日志文案等),提高人工逆向成本。

【边界(必须知道)】
  * 加密粒度 = 指令级字面量。只改 `const-string` / `const-string/jumbo`。
  * 字段的字符串值(`static final String S = "x"`)编译后就是 <clinit> 里的
    const-string + sput-object(R8 内联时是每个使用点各一条),**天然被覆盖**,
    不需要为字段写任何专门逻辑。
  * 字段名 / 方法名 / 类名 / 类型描述符属于 dex 结构引用,永不触碰。
  * 注解值(value = "x")不是 const-string 指令,天然不在扫描面。
  * 这是「防静态可见性」,不是密码学安全:密钥流派生材料同在包内,
    懂格式者仍可解。真正的密钥材料请走服务端/白盒方案。

【选类范围】
完全复用 dcc 那套规则解析(scripts/filter/rules-to-filter.py),语法一致:
  精确类名 com.app.MainActivity / com.test.** / com.test.* / com.test*
  activity*(需 --classes) / !排除 / # 注释 / 空行

【硬排除(用户要求:全量通配也不许动)】
即使规则写了 `**`,下列前缀的类一律不加密(系统类与框架依赖):
  android. androidx. android.support. com.android. com.google.android.
  dalvik. java. javax. kotlin. kotlinx. org.jetbrains.
  org.apache. org.json. org.w3c. org.xml. sun.
外加解密桩自身。`!` 排除行在非系统类范围内优先级最高;
命中系统前缀的类无条件硬排除(与 classify 的实际判定顺序一致)。

【算法(与 stub 里的 Java 实现必须逐字节一致,靠对拍测试锁定)】
  salt        : 16 字节随机(os.urandom / secrets),构建期生成
  payload     : Base64( idx_be24 || cipher )
                idx = 本构建内该密文的唯一编号(3 字节大端,上限 16,777,215)
  keystream   : ks_block(j) = SHA-256( salt || idx_be24 || byte(j) )
                cipher[i] = plain[i] ^ ks_block(i // 32)[i % 32]
  stub        : 注入 Lcom/nc/strdec/StrDec;,d(String) 解密并 intern()

【幂等】
  * 已加密的类插入了标记注释 `# nc-strdec-encrypted`(注释不进 dex),
    重跑时整类跳过,输出稳定。
  * 桩文件已存在时:解析回其中的 SALT_B64 继续使用,保证旧密文仍可解;
    若不是本工具生成的同名文件则 fail-fast,拒绝覆盖用户代码。

用法:
  encrypt-strings.py <解包目录> <规则文件> [--classes 类列表] \\
                     [--exclude-methods compiled_methods.txt] [--salt-hex HEX]
"""
import argparse
import base64
import hashlib
import importlib.util
import json
import os
import re
import secrets
import sys


_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))          # scripts/string-enc → 仓库根


def _load_module(name: str, rel_path: str):
    """文件名带连字符,不能常规 import → 与 mark-native.py 同款 importlib 加载。
    (报错三教训:基于 __file__ 的路径在脚本移动后必须重算,这里从本文件位置推算)"""
    path = os.path.join(_ROOT, rel_path)
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# 规则解析复用 dcc 侧同一脚本(用户要求"语法与 dex2c_rules 完全一致")
_RULES = _load_module('rules_to_filter', 'scripts/filter/rules-to-filter.py')
# smali 目录名约定复用 inject-loadlib 的单一真相(报错七:别处不要另写一份正则)
_INJECT = _load_module('inject_loadlib', 'scripts/inject/inject-loadlib.py')
SMALI_DIR_RE = _INJECT.SMALI_DIR_RE

# ── 解密桩约定 ──────────────────────────────────────────────────────
STUB_DESC = 'Lcom/nc/strdec/StrDec;'
STUB_PKG_DIR = ('com', 'nc', 'strdec')
STUB_FILE = 'StrDec.smali'
STUB_GEN_MARK = '# nc-strdec-gen v1'          # 桩文件内的生成标记(识别"这是我们写的")
CLASS_MARK = '# nc-strdec-encrypted'          # 已加密类的标记注释(幂等判定)
COMPONENTS_FILE = 'stringenc-components.json'  # 组件标记(报错十八式:元数据 save/restore)

# ── 硬排除:系统类与框架依赖(规则层不可突破) ─────────────────────────
SYSTEM_CLASS_PREFIXES = (
    'android.', 'androidx.', 'android.support.', 'com.android.',
    'com.google.android.', 'dalvik.', 'java.', 'javax.',
    'kotlin.', 'kotlinx.', 'org.jetbrains.',
    'org.apache.', 'org.json.', 'org.w3c.', 'org.xml.', 'sun.',
    # xCrash(爱奇艺 native 崩溃/ANR 捕获库):其 Java 层与 native 层通过 JNI 回调
    # 互相绑定(xcrash.NativeCrashHandler 的 native 方法 + callback),字符串或
    # 类/方法名一旦被加密/改写 → 崩溃捕获失效甚至自身崩溃。属"框架依赖",必须在
    # 规则层之上硬排除(与 kotlin./androidx. 同型)。前缀 'xcrash.' 覆盖其主包。
    'xcrash.',
)

IDX_MAX = (1 << 24) - 1                      # idx 占 3 字节

# ── 无价值串跳过:编译器生成的调试/内联标记(对比实验定性,2026-09) ────
# 背景:用户全量规则加密 3438 类后 app"进不去且无日志",而第三方字符串加密
# 工具同规则正常。解剖两产物发现关键差异:第三方工具内置"跳过名单",保留
# Kotlin/Compose/R8 desugar 编译器自动生成的调试标记串明文(仅 classes15 一个
# dex 就保留 1637 条 $i$f$ + 450 条 $this$ + 87 条 $changed);本工具此前
# 一个不漏全加密。这些串对 app 运行毫无作用(纯编译器/调试器记号),却让
# 解密桩为它们白付一份 keystream 成本与体积。跳过它们:体积更小、启动解密
# 更少,且不存在任何行为风险(没有人会依赖调试标记做业务判断)。
# 命中规则(逐明文串前缀判断,非类名):
#   $i$f$    — Kotlin inline 函数标记($i$f$functionName)
#   $i$a$    — Kotlin inline 匿名对象标记
#   $this$   — Kotlin 扩展/接收者标记($this$forEach 等)
#   $changed — Compose Composable 形参记号($changed / $changed\N 转义形态)
#   $stable  — Compose 稳定性记号
#   $-       — R8/D8 desugaring 合成 lambda 标记($-feat-$-lambda-... 形态)
_SKIP_STRING_PREFIXES = (
    '$i$f$', '$i$a$', '$this$', '$changed', '$stable', '$-',
)


def is_instrumentation_string(plain: str) -> bool:
    """编译器调试/内联标记串判定:命中即跳过加密(保留明文,不占 idx)。"""
    return plain.startswith(_SKIP_STRING_PREFIXES)


# ── 解密桩模板(纯 Java,无 so 依赖,无 <clinit> 外部依赖) ─────────────
STUB_TEMPLATE = '''.class public final Lcom/nc/strdec/StrDec;
.super Ljava/lang/Object;
.source "StrDec.java"

%GEN_MARK% -- generated by encrypt-strings.py, DO NOT EDIT
# keystream: ks_block(j) = SHA-256( SALT || idx_be24 || byte(j) ), byte-wise XOR
# payload  : Base64( idx_be24 || cipher ); decrypt at runtime and intern()

.field private static final SALT_B64:Ljava/lang/String; = "%SALT%"
# 性能优化(2026-09 对比实验):旧版每解一条字符串都重新
# MessageDigest.getInstance("SHA-256")(JCA Provider 查找)+ Base64.decode(SALT),
# 全量规则下首次解密风暴被放大数十倍。改为 <clinit> 初始化一次、全场复用:
#   SALT    — SALT_B64 解出的字节数组(xor() 直接 sget)
#   DIGEST  — 复用的 MessageDigest 实例(digest() 完成后自动 reset,可连续用)
# 算法与密钥流不变:ks_block(j) = SHA-256( SALT || idx_be24 || byte(j) ),旧密文
# 与新密文(同一 SALT)全部可解。注意 <clinit> 顺序:必须先初始化 SALT/DIGEST
# 再执行回填链(回填链会立刻调用 d() → xor() 消费这两个字段,见 <clinit> 内标记)。
.field private static final SALT:[B
.field private static final DIGEST:Ljava/security/MessageDigest;
%FIELDS%
.field private static final CACHE:Ljava/util/concurrent/ConcurrentHashMap;


# direct methods
.method static constructor <clinit>()V
    .registers 3

    new-instance v0, Ljava/util/concurrent/ConcurrentHashMap;

    invoke-direct {v0}, Ljava/util/concurrent/ConcurrentHashMap;-><init>()V

    sput-object v0, Lcom/nc/strdec/StrDec;->CACHE:Ljava/util/concurrent/ConcurrentHashMap;

    # SALT = Base64.decode(SALT_B64) —— 一次性初始化(见字段区性能注释)
    sget-object v0, Lcom/nc/strdec/StrDec;->SALT_B64:Ljava/lang/String;

    const/4 v1, 0x2

    invoke-static {v0, v1}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v0

    sput-object v0, Lcom/nc/strdec/StrDec;->SALT:[B

    # DIGEST = MessageDigest.getInstance("SHA-256") —— 一次性初始化
    const-string v0, "SHA-256"

    invoke-static {v0}, Ljava/security/MessageDigest;->getInstance(Ljava/lang/String;)Ljava/security/MessageDigest;

    move-result-object v0

    sput-object v0, Lcom/nc/strdec/StrDec;->DIGEST:Ljava/security/MessageDigest;

    # 必须在 SALT/DIGEST 就绪之后再执行回填链(它们会立刻触发 d()→xor())
    # ⚠️ 报错二十五防线:上面这行注释绝不许再写 CLINIT_FILL 的 %占位符% 形态 ——
    #    %占位符% 只能出现在【非注释行】的独立占位行;曾因注释里出现该占位符
    #    被 replace() 替换成真实指令,注入到类体顶层(非方法区)→ smali
    #    `no viable alternative at input 'sget-object'` → 整个重打包失败。
%CLINIT_FILL%
    return-void
.end method


.method public static d(Ljava/lang/String;)Ljava/lang/String;
    .registers 6

    sget-object v0, Lcom/nc/strdec/StrDec;->CACHE:Ljava/util/concurrent/ConcurrentHashMap;

    invoke-virtual {v0, p0}, Ljava/util/concurrent/ConcurrentHashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v1

    if-eqz v1, :cache_hit

    :try_start_dec
    invoke-static {p0}, Lcom/nc/strdec/StrDec;->dec(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v1
    :try_end_dec
    .catch Ljava/lang/Throwable; {:try_start_dec .. :try_end_dec} :catch_dec

    invoke-virtual {v0, p0, v1}, Ljava/util/concurrent/ConcurrentHashMap;->putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    if-eqz v2, :own_result

    check-cast v2, Ljava/lang/String;

    return-object v2

    :own_result
    return-object v1

    :catch_dec
    return-object p0

    :cache_hit
    check-cast v1, Ljava/lang/String;

    return-object v1
.end method


.method private static dec(Ljava/lang/String;)Ljava/lang/String;
    .registers 8

    const/4 v0, 0x2

    invoke-static {p0, v0}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v1

    const/4 v2, 0x0

    aget-byte v3, v1, v2

    and-int/lit16 v3, v3, 0xff

    shl-int/lit8 v3, v3, 0x10

    const/4 v4, 0x1

    aget-byte v5, v1, v4

    and-int/lit16 v5, v5, 0xff

    shl-int/lit8 v5, v5, 0x8

    or-int/2addr v3, v5

    const/4 v5, 0x2

    aget-byte v6, v1, v5

    and-int/lit16 v6, v6, 0xff

    or-int/2addr v3, v6

    invoke-static {v1, v3}, Lcom/nc/strdec/StrDec;->xor([BI)[B

    move-result-object v3

    new-instance v5, Ljava/lang/String;

    const-string v6, "UTF-8"

    invoke-direct {v5, v3, v6}, Ljava/lang/String;-><init>([BLjava/lang/String;)V

    invoke-virtual {v5}, Ljava/lang/String;->intern()Ljava/lang/String;

    move-result-object v5

    return-object v5
.end method


.method private static xor([BI)[B
    .registers 16

    array-length v0, p0

    add-int/lit8 v1, v0, -0x3

    new-array v2, v1, [B

    # 复用 <clinit> 初始化的实例/字段(性能优化,见字段区注释)。
    # digest() 返回后内部自动 reset,下一次 update 系列调用即干净状态。
    sget-object v3, Lcom/nc/strdec/StrDec;->DIGEST:Ljava/security/MessageDigest;

    sget-object v4, Lcom/nc/strdec/StrDec;->SALT:[B

    const/4 v5, 0x0

    const/4 v6, 0x0

    :loop_outer
    if-ge v5, v1, :done

    invoke-virtual {v3, v4}, Ljava/security/MessageDigest;->update([B)V

    shr-int/lit8 v7, p1, 0x10

    int-to-byte v7, v7

    invoke-virtual {v3, v7}, Ljava/security/MessageDigest;->update(B)V

    shr-int/lit8 v8, p1, 0x8

    int-to-byte v8, v8

    invoke-virtual {v3, v8}, Ljava/security/MessageDigest;->update(B)V

    int-to-byte v9, p1

    invoke-virtual {v3, v9}, Ljava/security/MessageDigest;->update(B)V

    int-to-byte v10, v6

    invoke-virtual {v3, v10}, Ljava/security/MessageDigest;->update(B)V

    invoke-virtual {v3}, Ljava/security/MessageDigest;->digest()[B

    move-result-object v10

    const/4 v11, 0x0

    const/16 v12, 0x20

    :loop_inner
    if-ge v11, v12, :next_block

    if-ge v5, v1, :next_block

    add-int/lit8 v13, v5, 0x3

    # ⚠️ 临时寄存器必须是【内层循环期间无依赖】的槽位,绝不能用 v14/v15:
    #    `.registers 16` + 双参 `([BI)` ⇒ 参数固定落在末尾寄存器 p0=v14、p1=v15
    #    (smali 规则:参数占最后 N 个寄存器)。旧版此处写 v14/v15 等价于直接改写
    #    形参本身 —— 第 1 轮把数组引用 p0 覆盖成刚读出的字节(int),第 2 轮
    #    `aget-byte v14, v14, v13` 就把这个 int 当数组引用解引用 ⇒ ART 只在
    #    null 时抛 NPE、非 null 非法引用直接 SIGSEGV(原生崩溃,Java catch 不住)
    #    ⇒ 任何 ≥2 字节的字符串解密即在 <clinit> 崩 → 闪退且无 FATAL 日志。
    #    v7/v8 是安全槽:外层循环里它们只做 MessageDigest.update 的临时值,
    #    进入内层时已死值,且每轮 `goto :loop_outer` 都会无条件重新赋值,
    #    不存在读到上一轮残留的风险(v7/v8 在内层循环期间无人读)。
    aget-byte v7, p0, v13

    aget-byte v8, v10, v11

    xor-int v7, v7, v8

    int-to-byte v7, v7

    aput-byte v7, v2, v5

    add-int/lit8 v5, v5, 0x1

    add-int/lit8 v11, v11, 0x1

    goto :loop_inner

    :next_block
    add-int/lit8 v6, v6, 0x1

    goto :loop_outer

    :done
    return-object v2
.end method
'''


# ── 解密桩自检:参数寄存器不得被当临时槽覆盖(报错二十二) ──────────────
#
# 为什么需要它:桩的 xor 曾把内层循环临时寄存器写成 v14/v15,而 `.registers 16`
# + 双参 `([BI)` 让 p0 恰好落在 v14、p1 落在 v15 ⇒ 指令静默改写形参本身,
# 汇编通过、静态对拍也过(算法对),只有运行期才崩(SIGSEGV/无 FATAL 日志)。
# "文字警告防不住文本级重写,只有机制能"——故把这条不变量做成构建期断言:
# 桩模板展开后,任何一条【写】指令的目标寄存器都不得落在参数寄存器区间内。
_NO_DEST_OPCODES = (
    'invoke-', 'if-', 'goto', 'return', 'throw', 'nop', 'move-exception',
    'monitor-', 'check-cast',          # check-cast 目标即源,不产生新值
)
_DEST_FIRST_RE = re.compile(
    r'^(?P<op>[a-z][a-z0-9/\-]*)'
    r'(?:\s+(?P<first>v\d+|p\d+))?')
_METHOD_HDR_RE = re.compile(
    r'^\.method\b[^\n]*?\b([A-Za-z_$][\w$]*|<init>|<clinit>)?\s*'
    r'\((?P<args>[^)]*)\)[^\n]*$')
_REGS_RE = re.compile(r'^[ \t]*\.(?P<kind>registers|locals)[ \t]+(?P<n>\d+)[ \t]*$')


def _param_reg_count(arg_desc: str, is_static: bool) -> int:
    """方法形参占用的寄存器数(J/D 占 2 个,this 占 1 个)。"""
    n = 0 if is_static else 1
    i = 0
    while i < len(arg_desc):
        c = arg_desc[i]
        if c == 'L':
            end = arg_desc.find(';', i)
            if end < 0:
                return -1
            i = end + 1
            n += 1
        elif c == '[':
            while i < len(arg_desc) and arg_desc[i] == '[':
                i += 1
            if i < len(arg_desc) and arg_desc[i] == 'L':
                end = arg_desc.find(';', i)
                if end < 0:
                    return -1
                i = end + 1
            else:
                i += 1
            n += 1
        elif c in 'JD':
            n += 2
            i += 1
        elif c in 'ZBSCIF':
            n += 1
            i += 1
        else:
            return -1
    return n


def _check_stub_registers(smali_text: str) -> None:
    """构建期断言:桩内无指令把参数寄存器当目标覆盖。违反即 fail-fast。"""
    lines = smali_text.splitlines()
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        hdr = _METHOD_HDR_RE.match(line.strip()) if line.strip().startswith('.method') else None
        if not hdr:
            i += 1
            continue
        method = hdr.group(1) or '(anonymous)'
        args = hdr.group('args')
        is_static = bool(re.search(r'\bstatic\b', line))
        nparams = _param_reg_count(args, is_static)
        # 收集方法体到 .end method
        j = i + 1
        body = []
        while j < n and not lines[j].strip() == '.end method':
            body.append(lines[j])
            j += 1
        # 找 .registers / .locals
        total = None
        for bl in body:
            m = _REGS_RE.match(bl)
            if m:
                total = int(m.group('n'))
                break
        if total is None or nparams < 0:
            i = j + 1
            continue
        # 参数寄存器编号(限于 v 编号):p0..pK 映射到 v(total-nparams)..v(total-1)
        param_lo = total - nparams        # 参数起始 v 编号
        for bl in body:
            s = bl.strip()
            # 显示跳过:空行 / 指令外元素(.directive)/ label(:x)/ 注释(#)—— 注释里
            # 出现 "aget-byte v14" 这类说明文字不得被当真实指令(否则说明文案会误伤自检)
            if not s or s.startswith(('.', ':', '#')):
                continue
            op = s.split()[0]
            if op.startswith(_NO_DEST_OPCODES):
                continue
            m = _DEST_FIRST_RE.match(s)
            if not m:
                continue
            dst = m.group('first')
            if not dst:
                continue
            if dst.startswith('p'):
                raise SystemExit(
                    f'❌ 解密桩自检失败:{method} 里 `{s}` 以参数寄存器 {dst} 为目标,\n'
                    f'   汇编/运行期会静默覆盖形参(报错二十二:闪退且无 FATAL 日志)。\n'
                    f'   请改用方法内确无依赖的局部寄存器槽。')
            vnum = int(dst[1:])
            if vnum >= param_lo:
                raise SystemExit(
                    f'❌ 解密桩自检失败:{method}(.registers {total}, 形参 {nparams} 个)里\n'
                    f'   `{s}` 以 {dst} 为目标,而参数寄存器是 v{param_lo}..v{total-1}'
                    f'(p0=v{param_lo})—— 相当于覆盖形参(报错二十二)。\n'
                    f'   请改用方法内确无依赖的局部寄存器槽。')
        i = j + 1


def _render_stub(salt_b64: str, field_decls: str, clinit_fill: str) -> str:
    """展开桩模板 + 自检。write_stub 走这里,保证任何路径都过校验。"""
    placeholders = ('%GEN_MARK%', '%SALT%', '%FIELDS%', '%CLINIT_FILL%')
    # 防线 1(报错二十五):模板的注释行里绝不许出现占位符 —— replace() 不认
    # 上下文,注释里的 %CLINIT_FILL% 会被替换成真实指令并注入类体顶层
    # (非方法区)→ smali `no viable alternative at input 'sget-object'`。
    for line in STUB_TEMPLATE.split('\n'):
        stripped = line.strip()
        if stripped.startswith('#') and any(p in line for p in placeholders):
            raise SystemExit(
                f'❌ 解密桩模板自检失败:注释行含占位符(报错二十五)——\n   {line}\n'
                f'   占位符只允许出现在非注释行;注释里的占位符会被 replace() '
                f'替换成真实指令并注入类体顶层,导致 smali 汇编失败。')
    content = (STUB_TEMPLATE
               .replace('%GEN_MARK%', STUB_GEN_MARK)
               .replace('%SALT%', salt_b64)
               .replace('%FIELDS%', field_decls)
               .replace('%CLINIT_FILL%', clinit_fill))
    # 防线 2:渲染后不许残留任何占位符(placeholder 漏替换/多写一样拦)
    for p in placeholders:
        if p in content:
            raise SystemExit(f'❌ 解密桩模板渲染后残留占位符 {p}(漏配 .replace?)')
    # 防线 3(报错二十五):类体顶层(非 .method 区)不许出现真实指令。
    # 走到这里说明占位符层面已干净,这条兜底拦住任何把指令注入非方法区的回归。
    in_method = False
    for line in content.split('\n'):
        s = line.strip()
        if s.startswith('.method'):
            in_method = True
        elif s == '.end method':
            in_method = False
        elif (in_method is False and s and not s.startswith(('.', '#'))
              and not s.startswith(':')):
            raise SystemExit(
                f'❌ 解密桩自检失败:类体顶层出现非指令行外的裸指令 ——\n   {line}\n'
                f'   指令只允许出现在 .method .. .end method 之间(报错二十五: '
                f'%CLINIT_FILL% 曾被替换进类体顶层 → no viable alternative)。')
    _check_stub_registers(content)
    return content


# ── smali 字符串字面量转义表(与 smali 汇编器的 unescape 对齐) ──────────
_UNESCAPE = {
    'n': '\n', 't': '\t', 'r': '\r', 'b': '\b', 'f': '\f',
    "'": "'", '"': '"', '\\': '\\',
}
_HEX = set('0123456789abcdefABCDEF')

# const-string 指令行:抓缩进 / jumbo / 目标寄存器 / 字面量起始
_INSTR_RE = re.compile(
    r'^(?P<indent>[ \t]*)const-string(?P<jumbo>/jumbo)?[ \t]+'
    r'(?P<dst>v\d+|p\d+)[ \t]*,[ \t]*"(?P<rest>.*)$')

# field 行携带的字符串字面量(R8 把 static final 常量折叠成 @value 注解形态)。
# 例: .field public static final URL:Ljava/lang/String; = "https://x"
# 类型必须以字段名后的 ':' 为锚(否则 [^;\s]+; 会把名字末尾的字符吞进类型)
_FIELD_RE = re.compile(
    r'^(?P<indent>[ \t]*)\.field(?P<mid>.*?)(?P<name>[A-Za-z_$][\w$]*):'
    r'(?P<type>[L\[][^\s]*?;)[ \t]*=[ \t]*"(?P<rest>.*)$')

# 值得加密的字段类型:String 本身,以及 String 数组(元素值同样是明文)
FIELD_STRING_TYPES = ('Ljava/lang/String;', '[Ljava/lang/String;')


def smali_unescape(text: str) -> str:
    """解码 smali 字符串字面量内容(两侧引号已剥掉)。

    识别不了转义时抛 ValueError(调用方跳过该条,绝不猜)——
    宁可漏一条也不静默改错字符串值。"""
    out = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if ch != '\\':
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= n:
            raise ValueError('结尾孤立反斜杠')
        esc = text[i]
        if esc == 'u':
            if i + 4 >= n:
                raise ValueError('\\u 转义不完整')
            hexs = text[i + 1:i + 5]
            if len(hexs) != 4 or any(c not in _HEX for c in hexs):
                raise ValueError('\\u 转义非 4 位十六进制')
            cp = int(hexs, 16)
            i += 5
            # baksmali 按 UTF-16 code unit 逐个转义:非 BMP 字符(emoji 等)
            # 输出成 \uD83D\uDE00 代理对。必须在这里合并成单个码点,
            # 否则 chr() 产生的孤立代理项后续 .encode('utf-8') 直接炸
            # (报错十九: UnicodeEncodeError: surrogates not allowed)。
            if 0xD800 <= cp <= 0xDBFF:                       # 高代理 → 必须跟低代理
                if i + 1 < n and text[i] == '\\' and text[i + 1] == 'u' \
                        and i + 6 <= n:
                    lo_hexs = text[i + 2:i + 6]
                    if len(lo_hexs) != 4 or any(c not in _HEX for c in lo_hexs):
                        raise ValueError('代理对低半 \\u 转义非法')
                    lo = int(lo_hexs, 16)
                    if not (0xDC00 <= lo <= 0xDFFF):
                        raise ValueError(f'高代理 \\u{cp:04X} 后未跟低代理(孤立代理项)')
                    out.append(chr(0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00)))
                    i += 6
                else:
                    raise ValueError(f'高代理 \\u{cp:04X} 后未跟低代理(孤立代理项)')
            elif 0xDC00 <= cp <= 0xDFFF:
                raise ValueError(f'孤立低代理 \\u{cp:04X}')
            else:
                out.append(chr(cp))
        elif esc in _UNESCAPE:
            out.append(_UNESCAPE[esc])
            i += 1
        else:
            raise ValueError(f'未知转义 \\{esc}')
    return ''.join(out)


def parse_const_string(line: str):
    """解析一条 const-string 指令行。
    返回 (match, literal_text, tail) 或 None(不是该指令/引号不闭合)。"""
    m = _INSTR_RE.match(line)
    if not m:
        return None
    rest = m.group('rest')
    i = 0
    while i < len(rest):
        c = rest[i]
        if c == '\\':
            i += 2
            continue
        if c == '"':
            break
        i += 1
    else:
        return None                                   # 引号不闭合,当异常行跳过
    return m, rest[:i], rest[i + 1:]


def parse_field_string(line: str):
    """解析携带字符串字面量的 .field 行(R8 折叠的 static final 常量)。
    返回 (match, literal_text, tail) 或 None。"""
    m = _FIELD_RE.match(line)
    if not m:
        return None
    if m.group('type') not in FIELD_STRING_TYPES:
        return None                                   # 只处理 String / String[] 字段
    rest = m.group('rest')
    i = 0
    while i < len(rest):
        c = rest[i]
        if c == '\\':
            i += 2
            continue
        if c == '"':
            break
        i += 1
    else:
        return None
    return m, rest[:i], rest[i + 1:]


def keystream(salt: bytes, idx: int, length: int) -> bytes:
    """与 stub xor() 逐字节一致的密钥流:块 j = SHA-256(salt || idx_be24 || j)。"""
    out = bytearray()
    j = 0
    idx_bytes = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    while len(out) < length:
        out += hashlib.sha256(salt + idx_bytes + bytes((j & 0xFF,))).digest()
        j += 1
    return bytes(out[:length])



    """与 stub xor() 逐字节一致的密钥流:块 j = SHA-256(salt || idx_be24 || j)。"""
    out = bytearray()
    j = 0
    idx_bytes = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    while len(out) < length:
        out += hashlib.sha256(salt + idx_bytes + bytes((j & 0xFF,))).digest()
        j += 1
    return bytes(out[:length])


def encrypt_payload(salt: bytes, idx: int, plain: bytes) -> str:
    """明文 → Base64( idx_be24 || cipher )。"""
    head = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    ks = keystream(salt, idx, len(plain))
    cipher = bytes(p ^ k for p, k in zip(plain, ks))
    return base64.b64encode(head + cipher).decode('ascii')


def desc_to_dot(desc: str) -> str:
    """Lcom/x/Y; → com.x.Y"""
    return desc[1:-1].replace('/', '.')


def build_matchers(rules_path: str, classes_file):
    """规则文件 → (include 正则表, exclude 正则表)。语法与 dcc 侧完全一致。"""
    with open(rules_path, encoding='utf-8') as fp:
        raw_rules = [line.strip() for line in fp]

    includes, excludes = [], []
    activity_mode = False
    for rule in raw_rules:
        if not rule or rule.startswith('#'):
            continue
        negate = rule.startswith('!')
        body = rule[1:].strip() if negate else rule
        if not body:
            continue
        if body == 'activity*':
            activity_mode = True
            if not classes_file:
                raise SystemExit('❌ 规则含 activity*,必须提供 --classes 类列表文件')
            for cls in _RULES.expand_activity_keyword(classes_file):
                pat = _RULES.class_rule_to_filter(cls[1:-1], False)
                (excludes if negate else includes).append(re.compile(pat))
            continue
        pat = _RULES.class_rule_to_filter(body, _RULES.has_wildcard(body))
        (excludes if negate else includes).append(re.compile(pat))
    return includes, excludes, activity_mode


def parse_compiled_methods(path: str):
    """compiled_methods.txt → {(类名, 方法名, 原型)}(格式同 §4.2,无箭头)。"""
    result = set()
    with open(path, encoding='utf-8') as fp:
        for line in fp:
            line = line.strip()
            if not line:
                continue
            m = re.match(r'^(L[^;]+;)([^(]+)(\(.*\)\S+)$', line)
            if m:
                result.add((m.group(1), m.group(2), m.group(3)))
    return result


def iter_smali_files(decompiled_dir: str):
    for root, _dirs, files in os.walk(decompiled_dir):
        parts = root[len(decompiled_dir):].lstrip(os.sep).split(os.sep)
        if any(SMALI_DIR_RE.match(p) for p in parts if p):
            for f in files:
                if f.endswith('.smali'):
                    yield os.path.join(root, f)


def class_desc_of(content: str):
    """取 .class 行的类描述符(同 mark-native.py 的取法)。"""
    for line in content.split('\n'):
        if line.startswith('.class'):
            m = re.search(r'L[^;\s]+;', line)
            if m:
                return m.group(0)
    return None


STUB_DOT = STUB_DESC[1:-1].replace('/', '.')

# 已加密条目的形态:const-string 紧跟本桩的 invoke-static(用于续跑时续 idx)。
# 必须同时认 `invoke-static {..}` 与 `invoke-static/range {.. .. ..}` 两种形态
# (报错二十一改注入形态后,/range 是新产物;若这里只认旧形态,max_existing_idx
# 会漏算 → 续跑 idx 从 0 重来 → salt+idx 相同 → keystream 复用)
_PAYLOAD_RE = re.compile(
    r'const-string(?:/jumbo)?[ \t]+(?:v\d+|p\d+)[ \t]*,[ \t]*"([^"\n]*)"\n'
    r'[ \t]*invoke-static(?:/range)? \{[^}\n]*\}, ' + re.escape(STUB_DESC) + r'->d\(')

# 字段常量回填引用(报错二十四改形态后):<clinit> 里的
#   sget-object vX, 本桩 ->F\d+
# (续跑时字段 idx 也要计入,否则新字段编号从 0 重来 → 相同 salt+idx →
# keystream 复用。旧形态 `= StrDec;->F\d+:` 是报错二十四的非法 FIELD 型
# static_value,已废弃,且被 _ILLEGAL_FIELD_INIT_RE 构建期断言拦截)
_FIELD_REF_RE = re.compile(
    # 回填引用形态(报错二十四):<clinit> 里的 sget-object vX, StrDec;->FNNNNNN
    r'sget-object[ \t]+(?:v\d+|p\d+),[ \t]*' + re.escape(STUB_DESC) + r'->F(\d+):')

# 非法形态断言(报错二十四):.field 初值绝不允许是 StrDec 字段引用。
# 该形态会被 smali 汇编成 FIELD 型(0x19) encoded static_value —— dex 规范
# 不允许的初值类型,ART 类初始化阶段(字节码执行之前)即失败 → 秒闪退且无日志。
_ILLEGAL_FIELD_INIT_RE = re.compile(
    r'^[ \t]*\.field[^\n]*=[ \t]*' + re.escape(STUB_DESC) + r'->F\d+:', re.M)


def is_system_class(cls_dot: str) -> bool:
    """系统类/框架依赖前缀判定(带点号前缀,不误伤 androidXxx 这种同前缀类)。"""
    return cls_dot.startswith(SYSTEM_CLASS_PREFIXES)


def classify(cls_dot: str, cls_desc: str, includes, excludes) -> str:
    """给类定性:no-match / system / excluded / stub / target。
    判定顺序:未命中 include → system(硬排除,规则层不可突破)→ stub →
    用户 ! 排除 → target。system 与 excluded 结果同为不加密,仅日志统计
    口径不同:命中系统前缀的类计入 skipped_system(即使用户 ! 排除行也
    拦不住硬排除的优先地位)。"""
    if not any(r.search(cls_desc) for r in includes):
        return 'no-match'
    if is_system_class(cls_dot):
        return 'system'
    if cls_dot == STUB_DOT:
        return 'stub'
    if any(r.search(cls_desc) for r in excludes):
        return 'excluded'
    return 'target'


def max_existing_idx(content: str) -> int:
    """已加密类里出现过的最大 idx(续跑时接着编号,避免 keystream 复用)。
    同时扫两类形态:指令密文(_PAYLOAD_RE)与回填引用(_FIELD_REF_RE)。"""
    biggest = -1
    for m in _PAYLOAD_RE.finditer(content):
        try:
            raw = base64.b64decode(m.group(1), validate=True)
        except Exception:
            continue
        if len(raw) >= 3:
            biggest = max(biggest, int.from_bytes(raw[:3], 'big'))
    for m in _FIELD_REF_RE.finditer(content):
        biggest = max(biggest, int(m.group(1), 10))
    return biggest


def find_stub_path(decompiled_dir: str):
    """在 smali*/ 里找桩文件(只有解包目录下、且位于桩包路径中的才算)。"""
    for root, _dirs, files in os.walk(decompiled_dir):
        parts = root[len(decompiled_dir):].lstrip(os.sep).split(os.sep)
        if not any(SMALI_DIR_RE.match(p) for p in parts if p):
            continue
        if STUB_FILE in files and root.endswith(os.path.join(*STUB_PKG_DIR)):
            return os.path.join(root, STUB_FILE)
    return None


def read_existing_salt(decompiled_dir: str):
    """已存在且是本工具生成的桩 → 复用其 SALT_B64(否则旧密文解不开)。
    返回 (salt_bytes 或 None, 是否需要写桩)。同名非本工具文件 → fail-fast。"""
    stub_path = find_stub_path(decompiled_dir)
    if not stub_path:
        return None, True
    with open(stub_path, encoding='utf-8') as fp:
        content = fp.read()
    if STUB_GEN_MARK not in content:
        raise SystemExit(f'❌ 已存在同名类但非本工具生成,拒绝覆盖: {stub_path}\n'
                         f'   请改名或移走用户的 {STUB_DESC} 后重试')
    m = re.search(r'SALT_B64:Ljava/lang/String;[ \t]*=[ \t]*"([A-Za-z0-9+/=]+)"', content)
    if not m:
        raise SystemExit(f'❌ 桩文件缺少 SALT_B64,无法复用: {stub_path}')
    return base64.b64decode(m.group(1)), False


def read_existing_stub_fields(decompiled_dir: str):
    """读回已存在桩里登记的字段常量 [(name, payload)](报错二十式:
    复用桩时本次产生新字段,必须把旧字段一并带上重写桩,否则类里引用了
    F000005 而桩里没有声明 → 汇编 NoSuchFieldError / 运行期 null)。"""
    stub_path = find_stub_path(decompiled_dir)
    if not stub_path:
        return []
    with open(stub_path, encoding='utf-8') as fp:
        content = fp.read()
    if STUB_GEN_MARK not in content:
        return []                                     # 调用方已 fail-fast,防御性兜底
    fields = []
    for m in re.finditer(
            r'\.field public static final (F\d+):Ljava/lang/String;\n'
            r'\.field private static final C_\1:Ljava/lang/String; = "'
            r'([A-Za-z0-9+/=]+)"', content):
        fields.append((m.group(1), m.group(2)))
    return fields


def _pick_smali_root(decompiled_dir: str) -> str:
    """桩落在哪个 smali 目录:优先 smali/,否则第一个 smali*/。"""
    preferred = os.path.join(decompiled_dir, 'smali')
    if os.path.isdir(preferred):
        return preferred
    for name in sorted(os.listdir(decompiled_dir)):
        if SMALI_DIR_RE.match(name) and os.path.isdir(os.path.join(decompiled_dir, name)):
            return os.path.join(decompiled_dir, name)
    raise SystemExit(f'❌ 解包目录下找不到 smali/ 或 smali_classes*/ : {decompiled_dir}')


def write_components_stamp(decompiled_dir: str, cls_desc: str) -> str:
    """记录本次注入的组件(类名 + 源文件路径)。

    报错十八教训:流水线中途会丢失信息(回编降级抹掉 dex 版本),必须在丢失前 save。
    这里同理 —— apktool 重打包会重新分派 dex 号,唯一稳定的定位依据是
    "描述符 + 源文件路径"对。落盘后,`clean` 子命令可长期正确清理残留的桩类
    (例如本次运行一条都没加密、旧桩却还在)。"""
    root = _pick_smali_root(decompiled_dir)
    payload = {
        'version': 1,
        'classes': [{
            'desc': cls_desc,
            'src': os.path.relpath(
                os.path.join(root, *STUB_PKG_DIR, STUB_FILE), decompiled_dir),
        }],
    }
    path = os.path.join(decompiled_dir, COMPONENTS_FILE)
    with open(path, 'w', encoding='utf-8') as fp:
        json.dump(payload, fp, ensure_ascii=False, indent=2)
        fp.write('\n')
    return path


def clean_components(decompiled_dir: str) -> int:
    """按组件标记删除残留的注入物(解密桩)。幂等,清完删标记文件。

    只删标记里登记的路径,且要求两者同时满足「路径在本解包目录内」+
    「文件内容带本工具生成标记」—— 绝不误删用户自己的类。

    fail-fast(报错二十):删桩前先扫全解包目录,若存在仍引用桩的已加密类
    (CLASS_MARK + ->d( / ->F\\d+: 引用),说明上一轮加密产物没被恢复/重建,
    此时删桩会留下半加密目录 → 汇编失败或运行期 NoClassDefFoundError。
    正常流水线每次全新解包不会触发;本地反复调试会踩,拒绝优于静默坏产物。"""
    path = os.path.join(decompiled_dir, COMPONENTS_FILE)
    if not os.path.isfile(path):
        return 0
    # 半加密目录探测:带 CLASS_MARK 且引用本桩的类
    tainted = []
    for cls_path in iter_smali_files(decompiled_dir):
        try:
            with open(cls_path, encoding='utf-8') as fp:
                content = fp.read()
        except OSError:
            continue
        if CLASS_MARK in content and (STUB_DESC + '->d(' in content
                                      or _FIELD_REF_RE.search(content)):
            tainted.append(cls_path)
    if tainted:
        sample = os.path.relpath(tainted[0], decompiled_dir)
        raise SystemExit(
            f'❌ 解包目录存在仍引用解密桩的已加密类({len(tainted)} 个,如 {sample}),\n'
            f'   删除桩会留下半加密目录。请重新解包(全新 mktemp 目录)或先用 git '
            f'恢复原始 smali,\n   再跑本命令。加密类必须在桩存在的前提下进产物。')
    with open(path, encoding='utf-8') as fp:
        payload = json.load(fp)
    root_abs = os.path.abspath(decompiled_dir)
    removed = 0
    for entry in payload.get('classes', []):
        target = os.path.abspath(os.path.join(decompiled_dir, entry.get('src', '')))
        if not target.startswith(root_abs + os.sep):
            continue                                # 标记被篡改 → 绝不越界删除
        if not os.path.isfile(target):
            continue
        with open(target, encoding='utf-8') as fp:
            if STUB_GEN_MARK not in fp.read():
                continue                            # 不是我们的文件 → 不删
        os.remove(target)
        removed += 1
    os.remove(path)
    return removed


def write_stub(decompiled_dir: str, salt: bytes, stub_fields) -> str:
    """写解密桩。stub_fields: [(字段名, 密文 base64)] —— R8 折叠的 static final
    String 常量改成了对这些字段的引用,字段值由桩的 <clinit> 运行期解密填入。"""
    root = _pick_smali_root(decompiled_dir)
    stub_dir = os.path.join(root, *STUB_PKG_DIR)
    os.makedirs(stub_dir, exist_ok=True)
    stub_path = os.path.join(stub_dir, STUB_FILE)

    # 字段声明 + <clinit> 里的解密赋值
    field_decls = ''.join(
        f'\n.field public static final {name}:Ljava/lang/String;\n'
        f'.field private static final C_{name}:Ljava/lang/String; = "{payload}"\n'
        for name, payload in stub_fields)
    clinit_fill = ''.join(
        f'\n    sget-object v0, {STUB_DESC}->C_{name}:Ljava/lang/String;\n'
        f'\n    invoke-static {{v0}}, {STUB_DESC}'
        f'->d(Ljava/lang/String;)Ljava/lang/String;\n'
        f'\n    move-result-object v0\n'
        f'\n    sput-object v0, {STUB_DESC}->{name}:Ljava/lang/String;\n'
        for name, _payload in stub_fields)

    # 走 _render_stub(内含寄存器自检,报错二十二):任何写桩路径都过校验
    content = _render_stub(
        base64.b64encode(salt).decode('ascii'),
        field_decls if stub_fields else '',
        clinit_fill if stub_fields else '')
    with open(stub_path, 'w', encoding='utf-8') as fp:
        fp.write(content)
    return stub_path


def process_file(path: str, cls_desc: str, includes, excludes,
                 exclude_methods, salt: bytes, next_idx: int):
    """就地加密一个 .smali 文件。返回 (改动字符串数, 新 next_idx, stub_fields, field_backfills)。
    stub_fields: [(桩字段名, 密文)](写进桩 <clinit> 的密文常量);
    field_backfills: [{stub_field, owner_cls, field, type}](需要回填的目标字段)。"""
    with open(path, encoding='utf-8') as fp:
        content = fp.read()
    if CLASS_MARK in content:
        # 幂等:整类已处理。但仍要把它用过的 idx 计入,续跑时不重复编号
        return 0, max(next_idx, max_existing_idx(content) + 1), [], []

    lines = content.split('\n')
    out = []
    cur_method = None
    hits = 0
    idx = next_idx
    stub_fields = []          # 需要生成的桩字段: [(字段名, 密文)]
    field_backfills = []      # 报错二十四:<clinit> 回填登记
    li = 0
    n_lines = len(lines)
    while li < n_lines:
        line = lines[li]
        li += 1
        stripped = line.strip()
        if stripped.startswith('.method'):
            # 同 mark-native.py:名字取括号前紧邻一段,防参数里嵌方法引用的贪婪误判
            m = re.match(r'\.method\s+(.*\S)\s*(\(.*\)\S+)\s*$', stripped)
            if m:
                toks = m.group(1).split()
                cur_method = (toks[-1], m.group(2))
            else:
                cur_method = None
            out.append(line)
            continue
        if stripped == '.end method':
            cur_method = None
            out.append(line)
            continue

        # R8 折叠的 static final String 常量: .field ... = "明文"
        # (报错二十四)字段初值【保持原字面量不动】—— 绝不允许改成
        # `= StrDec;->FNNNNNN` 引用形态:那会被汇编成 FIELD 型(0x19)
        # encoded static_value,dex 规范不允许 → ART 类初始化阶段
        # (字节码执行之前)即失败,秒闪退且无任何日志。
        # 明文的"隐藏"改由回填实现:在所属类 <clinit> 里注入
        # sget-object(桩字段) + sput-object(本字段),运行期用解密结果
        # 覆盖字面量初值。桩自身 <clinit> 填 F 字段用的就是同一套合法形态。
        fparsed = parse_field_string(line)
        if fparsed and cur_method is None:
            fm, fliteral, ftail = fparsed
            try:
                fplain = smali_unescape(fliteral)
            except ValueError as exc:
                print(f'⚠️ 跳过无法安全解析的字段字面量({exc}): {path}', file=sys.stderr)
                out.append(line)
                continue
            if idx > IDX_MAX:
                raise SystemExit(f'❌ 加密字符串数超过 {IDX_MAX}(idx 3 字节上限),请缩小规则范围')
            if is_instrumentation_string(fplain):
                # 编译器调试/内联标记:保留明文字面量,不登记回填(见常量区说明)
                out.append(line)
                continue
            field_name = f'F{idx:06d}'          # 用全局 idx 命名,跨类天然唯一
            stub_fields.append((field_name, encrypt_payload(salt, idx,
                                                            fplain.encode('utf-8'))))
            # 原字段行原样保留(初值仍是明文字面量,产物形态合法);
            # 回填信息交给 main() 在 <clinit> 注入时消费
            out.append(line)
            field_backfills.append({
                'stub_field': field_name,
                'owner_cls': cls_desc,           # Lcom/x/Y; 形式
                'field': fm.group('name'),
                'type': fm.group('type'),
            })
            idx += 1
            hits += 1
            continue

        excluded_by_dex2c = bool(
            cur_method and (cls_desc, cur_method[0], cur_method[1]) in exclude_methods)

        # 已加密条目(解密桩可能来自上一次运行)→ 跳过,并续用序号,
        # 避免把密文当明文再加密一次
        if STUB_DESC + '->d(' in line:
            out.append(line)
            midx = max_existing_idx(line + '\n')
            if midx >= 0:
                idx = max(idx, midx + 1)
            continue

        parsed = parse_const_string(line)
        if not parsed:
            out.append(line)
            continue
        # 逐行前瞻防二次加密(报错二十式双保险):即使类标记被外部工具删掉,
        # 密文 const-string 的下一行必是本桩的 invoke-static ...->d(...),
        # 命中即连同密文行原样保留(与上方 ->d( 分支同样的续 idx 语义)
        if li < n_lines and STUB_DESC + '->d(' in lines[li]:
            out.append(line)
            midx = max_existing_idx(line + '\n' + lines[li] + '\n')
            if midx >= 0:
                idx = max(idx, midx + 1)
            continue
        if excluded_by_dex2c:
            out.append(line)                            # 该方法将被 dex2c 抽走 → 不浪费体积
            continue

        m, literal, tail = parsed
        try:
            plain = smali_unescape(literal)
        except ValueError as exc:
            print(f'⚠️ 跳过无法安全解析的字符串({exc}): {path}', file=sys.stderr)
            out.append(line)
            continue

        if idx > IDX_MAX:
            raise SystemExit(f'❌ 加密字符串数超过 {IDX_MAX}(idx 3 字节上限),请缩小规则范围')
        if is_instrumentation_string(plain):
            # 编译器调试/内联标记:保留明文 const-string(见常量区说明)
            out.append(line)
            continue

        payload = encrypt_payload(salt, idx, plain.encode('utf-8'))
        jumbo = m.group('jumbo') or ''
        indent = m.group('indent')
        dst = m.group('dst')
        out.append(f'{indent}const-string{jumbo} {dst}, "{payload}"{tail}')
        # 寄存器宽度陷阱(报错二十一):const-string 是 21c 格式(8 位寄存器,
        # v0–v255),而 invoke-* 是 35c 格式(寄存器列表仅 4 位,上限 v15)。
        # 原 const-string 的目标寄存器可合法取到 v16+(大方法/Compose),或写成
        # pN 而换算后编号 ≥16 → 直接 {dst} 会被 smali 汇编器拒绝,整个重打包
        # 失败("Invalid register: vNN. Must be between v0 and v15" /
        # "The maximum allowed register in this context is list of registers is v15")。
        # 统一用 /range:单寄存器 range 恒连续、dex 中同为 3 个 code unit(无体积
        # 代价),且对 v/p 两种写法都合法 → 无需解析 .registers/.locals 做换算。
        out.append(f'{indent}invoke-static/range {{{dst} .. {dst}}}, '
                   f'{STUB_DESC}->d(Ljava/lang/String;)Ljava/lang/String;')
        out.append(f'{indent}move-result-object {dst}')
        idx += 1
        hits += 1

    if hits == 0:
        # 没有新加密,但可能只命中了"已加密条目跳过"分支(类标记丢失 +
        # 三行形态)—— 此时 idx 已被续到旧密文之后,必须带回去,
        # 否则续跑时新条目从 0 编号 → keystream 复用(报错二十式)
        return 0, max(next_idx, idx), [], []

    # 插幂等标记注释(注释不进 dex)
    final = []
    marked = False
    for ln in out:
        final.append(ln)
        if not marked and ln.lstrip().startswith('.class'):
            final.append(f'{CLASS_MARK} (do not remove)')
            marked = True
    with open(path, 'w', encoding='utf-8') as fp:
        fp.write('\n'.join(final))
    return hits, idx, stub_fields, field_backfills


def inject_clinit_backfills(path: str, backfills) -> bool:
    """报错二十四:在 path 所属类的 <clinit> 末尾(return-void 之前)注入回填链:

        sget-object vX, Lcom/nc/strdec/StrDec;->FNNNNNN:Ljava/lang/String;
        sput-object vX, <owner>;-><field>:<type>

    运行期类初始化时用解密结果覆盖字面量初值 —— 这是 dex 规范允许的唯一
    "运行期算字段值"形态(桩自身 <clinit> 填 F 字段即此形态)。
    <clinit> 不存在则新建(.locals 1,寄存器只占 v0,恒在 35c/21c 上限内)。
    返回是否发生了注入。"""
    with open(path, encoding='utf-8') as fp:
        content = fp.read()

    # 组装注入体(全部走 v0 —— 回填链内部自依赖,任何 <clinit> 都容得下一个 v0;
    # 已有 <clinit> 的 .locals 可能是 0,新建时用 1,已有时若 .locals 0 需抬到 1)
    lines = content.split('\n')
    clinit_idx = None          # '.method static constructor <clinit>()V' 行号
    clinit_end = None          # 对应 '.end method' 行号
    clinit_locals = None
    for i, ln in enumerate(lines):
        s = ln.strip()
        if s.startswith('.method') and 'constructor' in s and '<clinit>' in s:
            clinit_idx = i
            # 找 .locals / .registers 与方法结束
            for j in range(i + 1, len(lines)):
                sj = lines[j].strip()
                mloc = re.match(r'\.(?:registers|locals)[ \t]+(\d+)$', sj)
                if mloc and clinit_locals is None:
                    clinit_locals = int(mloc.group(1))
                if sj == '.end method':
                    clinit_end = j
                    break
            break
    has_clinit = clinit_idx is not None and clinit_end is not None

    fill_lines = []
    for bf in backfills:
        fill_lines.append(
            f'    sget-object v0, {STUB_DESC}->{bf["stub_field"]}:{bf["type"]}')
        fill_lines.append(
            f'    sput-object v0, {bf["owner_cls"]}->{bf["field"]}:{bf["type"]}')

    if has_clinit:
        if clinit_locals is not None and clinit_locals < 1:
            # <clinit> .locals 0 也要用 v0 → 抬到 1
            for j in range(clinit_idx, clinit_end):
                if re.match(r'[ \t]*\.(?:registers|locals)[ \t]+0[ \t]*$', lines[j]):
                    lines[j] = lines[j].replace('0', '1', 1)
                    break
        # 找 <clinit> 里的 return-void,插到它之前(若无 return-void 则插到末尾)
        insert_at = clinit_end
        for j in range(clinit_end - 1, clinit_idx, -1):
            if lines[j].strip() == 'return-void':
                insert_at = j
                break
        lines[insert_at:insert_at] = fill_lines
    else:
        # 无 <clinit> → 在类体末尾追加一个最小的
        lines.append('')
        lines.append('.method static constructor <clinit>()V')
        lines.append('    .locals 1')
        lines.append('')
        lines.extend(fill_lines)
        lines.append('')
        lines.append('    return-void')
        lines.append('.end method')

    with open(path, 'w', encoding='utf-8') as fp:
        fp.write('\n'.join(lines))
    return True


def main() -> int:
    argv = sys.argv[1:]
    # 子命令:clean(按组件标记清残留,幂等) | encrypt(默认)
    if argv and argv[0] == 'clean':
        if len(argv) != 2:
            print('用法: encrypt-strings.py clean <解包目录>', file=sys.stderr)
            return 1
        removed = clean_components(argv[1])
        print(f'✅ 清理残留解密桩: {removed} 个')
        return 0

    ap = argparse.ArgumentParser(
        description='dex 层字符串常量加密(按 dcc 同款规则选类,注入 Java 解密桩)')
    ap.add_argument('decompiled', help='apktool 解包目录(含 smali*/)')
    ap.add_argument('rules', help='类名规则文件(语法同 dex2c_rules)')
    ap.add_argument('--classes', help='activity* 展开所需类列表(make-filter-from-apk 产物)')
    ap.add_argument('--exclude-methods',
                    help='compiled_methods.txt:这些方法将被 dex2c 抽走,跳过不加密')
    ap.add_argument('--salt-hex', help='固定 salt(16 字节 hex),仅供测试/复现')
    ap.add_argument('--quiet', action='store_true', help='只打错误')
    args = ap.parse_args(argv)

    if not os.path.isdir(args.decompiled):
        print(f'❌ 解包目录不存在: {args.decompiled}', file=sys.stderr)
        return 1
    if not os.path.isfile(args.rules):
        print(f'❌ 规则文件不存在: {args.rules}', file=sys.stderr)
        return 1

    includes, excludes, activity_mode = build_matchers(args.rules, args.classes)
    if not includes:
        print('❌ 规则文件没有产生任何包含规则(只有排除/注释?)', file=sys.stderr)
        return 1

    exclude_methods = set()
    if args.exclude_methods:
        if not os.path.isfile(args.exclude_methods):
            print(f'❌ --exclude-methods 文件不存在: {args.exclude_methods}', file=sys.stderr)
            return 1
        exclude_methods = parse_compiled_methods(args.exclude_methods)

    if args.salt_hex:
        salt = bytes.fromhex(args.salt_hex)
        if len(salt) != 16:
            print('❌ --salt-hex 必须是 16 字节(32 位 hex)', file=sys.stderr)
            return 1
    else:
        salt = secrets.token_bytes(16)

    # 幂等/复用:已有桩则沿用其 salt(否则旧密文解不开)
    existing_salt, need_write_stub = read_existing_salt(args.decompiled)
    if existing_salt is not None:
        salt = existing_salt

    total_str, total_cls, idx = 0, 0, 0
    skipped_system = skipped_excluded = skipped_stub = 0
    all_stub_fields = []
    all_backfills = []
    for path in sorted(iter_smali_files(args.decompiled)):
        with open(path, encoding='utf-8') as fp:
            content = fp.read()
        cls_desc = class_desc_of(content)
        if not cls_desc:
            continue
        cls_dot = desc_to_dot(cls_desc)
        verdict = classify(cls_dot, cls_desc, includes, excludes)
        if verdict == 'no-match':
            continue
        if verdict == 'system':
            skipped_system += 1
            continue
        if verdict == 'excluded':
            skipped_excluded += 1
            continue
        if verdict == 'stub':
            skipped_stub += 1
            continue
        n, idx, fields, backfills = process_file(path, cls_desc, includes, excludes,
                                                 exclude_methods, salt, idx)
        if n:
            total_str += n
            total_cls += 1
            all_stub_fields.extend(fields)
            if backfills:
                all_backfills.extend(backfills)
                # 报错二十四:字段初值已是合法明文字面量,回填走 <clinit>
                # (同文件立即注入 —— process_file 已重写并加幂等标记,
                #  这里重读注入,两条链互不干扰)
                inject_clinit_backfills(path, backfills)

    if need_write_stub and total_str > 0:
        stub_path = write_stub(args.decompiled, salt, all_stub_fields)
        stamp = write_components_stamp(args.decompiled, STUB_DESC)
        if not args.quiet:
            print(f'  🔧 注入解密桩: {os.path.relpath(stub_path, args.decompiled)}'
                  f' (组件标记 {os.path.basename(stamp)}'
                  f'{f", 字段常量 {len(all_stub_fields)} 个" if all_stub_fields else ""})')
    elif total_str > 0 and all_stub_fields:
        # 复用已有桩但本次产生了新字段(报错二十式):旧字段+新字段合并重写桩。
        # 旧桩若缺字段声明,类里 <clinit> 的 sget-object ->F\d+: 引用会汇编失败/运行期取到 null。
        old_fields = read_existing_stub_fields(args.decompiled)
        merged = {name: payload for name, payload in old_fields}
        for name, payload in all_stub_fields:
            if name in merged and merged[name] != payload:
                raise SystemExit(
                    f'❌ 字段 {name} 与旧桩密文不一致(盐复用冲突),请清理解包目录后重跑')
        merged.update({name: payload for name, payload in all_stub_fields})
        combined = sorted(merged.items())              # 按字段名(=idx)稳定排序
        write_stub(args.decompiled, salt, combined)
        write_components_stamp(args.decompiled, STUB_DESC)
        if not args.quiet:
            print(f'  🔧 重写解密桩(合并字段): 新 {len(all_stub_fields)} 个,'
                  f' 保留旧 {len(old_fields)} 个, 共 {len(combined)} 个')
    # need_write_stub 但一条都没加密 → 不注入桩(不给产物塞无用类,且省掉 dex 内新类)

    # 报错二十四 构建期防线:任何产物 .field 初值都不允许是 StrDec 字段引用
    # (FIELD 型 0x19 encoded static_value,ART 类初始化即失败 → 秒闪退无日志)。
    # 此前版本曾把字段初值改写成该形态且 apktool 编译器宽容放行,教训:
    # 汇编器宽容 ≠ 产物合法。每次跑完都复读全包做硬断言,违反即 fail-fast。
    illegal = []
    for cls_path in iter_smali_files(args.decompiled):
        try:
            with open(cls_path, encoding='utf-8') as fp:
                c = fp.read()
        except OSError:
            continue
        if _ILLEGAL_FIELD_INIT_RE.search(c):
            illegal.append(cls_path)
    if illegal:
        sample = os.path.relpath(illegal[0], args.decompiled)
        raise SystemExit(
            f'❌ 构建期断言失败:{len(illegal)} 个文件出现非法字段初值形态 '
            f'(.field ... = {STUB_DESC}->F...):\n   {sample}\n'
            f'   该形态会被汇编成 FIELD 型(0x19) static_value,ART 类初始化即闪退'
            f'(报错二十四)。字段常量回填必须走 <clinit> 的 sget/sput 链。')

    if not args.quiet:
        if activity_mode:
            print('ℹ️ 规则含 activity*,已按 --classes 展开')
        if skipped_system:
            print(f'ℹ️ 命中规则但被硬排除(系统/框架依赖类)跳过: {skipped_system} 个类')
        if skipped_excluded:
            print(f'ℹ️ 被用户 ! 规则排除跳过: {skipped_excluded} 个类')
        if skipped_stub:
            print(f'ℹ️ 解密桩自身跳过: {skipped_stub} 个')
        print(f'✅ 字符串加密完成: {total_str} 条 / {total_cls} 个类'
              f' (salt={base64.b64encode(salt).decode("ascii")[:8]}..., '
              f'桩={"已注入" if (need_write_stub and total_str) else "复用/未用"})')
        if total_str == 0:
            print('⚠️ 没有任何字符串被加密 —— 检查规则是否命中(系统/依赖类会被硬排除)',
                  file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
