#!/usr/bin/env python3
"""encrypt-strings.py — dex 层字符串常量加密(构建期异或 + 运行期 Java 解密桩)

【这是什么】
把「用户选中类」里 dex 的字符串常量(const-string 字面量)在构建期加密,
运行期由注入的纯 Java 解密桩解密。目标是让 `strings`/静态特征扫描看不到
源码里写死的明文(URL/API key/日志文案等),提高人工逆向成本。

【边界(必须知道)】
  * 加密粒度 = 指令级字面量。只改 `const-string` / `const-string/jumbo`。
  * 字段的字符串值(`static final String S = "x"`)编译后就是 <clinit> 里的
    const-string + sput-object(R8 内联时是每个使用点各一条),**天然被覆盖**,
    不需要为字段写任何专门逻辑。
  * 字段名 / 方法名 / 类名 / 类型描述符属于 dex 结构引用,永不触碰。
  * 注解值(value = "x")不是 const-string 指令,天然不在扫描面。
  * 这是「防静态可见性」,不是密码学安全:密钥流派生材料同在包内,
    懂格式者仍可解。真正的密钥材料请走服务端/白盒方案。

【选类范围】
完全复用 dcc 那套规则解析(scripts/filter/rules-to-filter.py),语法一致:
  精确类名 com.app.MainActivity / com.test.** / com.test.* / com.test*
  activity*(需 --classes) / !排除 / # 注释 / 空行

【硬排除(用户要求:全量通配也不许动)】
即使规则写了 `**`,下列前缀的类一律不加密(系统类与框架依赖):
  android. androidx. android.support. com.android. com.google.android.
  dalvik. java. javax. kotlin. kotlinx. org.jetbrains.
  org.apache. org.json. org.w3c. org.xml. sun.
外加解密桩自身。用户 `!` 排除行优先级最高。

【算法(与 stub 里的 Java 实现必须逐字节一致,靠对拍测试锁定)】
  salt        : 16 字节随机(os.urandom / secrets),构建期生成
  payload     : Base64( idx_be24 || cipher )
                idx = 本构建内该密文的唯一编号(3 字节大端,上限 16,777,215)
  keystream   : ks_block(j) = SHA-256( salt || idx_be24 || byte(j) )
                cipher[i] = plain[i] ^ ks_block(i // 32)[i % 32]
  stub        : 注入 Lcom/nc/strdec/StrDec;,d(String) 解密并 intern()

【幂等】
  * 已加密的类插入了标记注释 `# nc-strdec-encrypted`(注释不进 dex),
    重跑时整类跳过,输出稳定。
  * 桩文件已存在时:解析回其中的 SALT_B64 继续使用,保证旧密文仍可解;
    若不是本工具生成的同名文件则 fail-fast,拒绝覆盖用户代码。

用法:
  encrypt-strings.py <解包目录> <规则文件> [--classes 类列表] \\
                     [--exclude-methods compiled_methods.txt] [--salt-hex HEX]
"""
import argparse
import base64
import hashlib
import importlib.util
import json
import os
import re
import secrets
import sys


_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))          # scripts/string-enc → 仓库根


def _load_module(name: str, rel_path: str):
    """文件名带连字符,不能常规 import → 与 mark-native.py 同款 importlib 加载。
    (报错三教训:基于 __file__ 的路径在脚本移动后必须重算,这里从本文件位置推算)"""
    path = os.path.join(_ROOT, rel_path)
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# 规则解析复用 dcc 侧同一脚本(用户要求"语法与 dex2c_rules 完全一致")
_RULES = _load_module('rules_to_filter', 'scripts/filter/rules-to-filter.py')
# smali 目录名约定复用 inject-loadlib 的单一真相(报错七:别处不要另写一份正则)
_INJECT = _load_module('inject_loadlib', 'scripts/inject/inject-loadlib.py')
SMALI_DIR_RE = _INJECT.SMALI_DIR_RE

# ── 解密桩约定 ──────────────────────────────────────────────────────
STUB_DESC = 'Lcom/nc/strdec/StrDec;'
STUB_PKG_DIR = ('com', 'nc', 'strdec')
STUB_FILE = 'StrDec.smali'
STUB_GEN_MARK = '# nc-strdec-gen v1'          # 桩文件内的生成标记(识别"这是我们写的")
CLASS_MARK = '# nc-strdec-encrypted'          # 已加密类的标记注释(幂等判定)
COMPONENTS_FILE = 'stringenc-components.json'  # 组件标记(报错十八式:元数据 save/restore)

# ── 硬排除:系统类与框架依赖(规则层不可突破) ─────────────────────────
SYSTEM_CLASS_PREFIXES = (
    'android.', 'androidx.', 'android.support.', 'com.android.',
    'com.google.android.', 'dalvik.', 'java.', 'javax.',
    'kotlin.', 'kotlinx.', 'org.jetbrains.',
    'org.apache.', 'org.json.', 'org.w3c.', 'org.xml.', 'sun.',
)

IDX_MAX = (1 << 24) - 1                      # idx 占 3 字节

# ── 解密桩模板(纯 Java,无 so 依赖,无 <clinit> 外部依赖) ─────────────
STUB_TEMPLATE = '''.class public final Lcom/nc/strdec/StrDec;
.super Ljava/lang/Object;
.source "StrDec.java"

%GEN_MARK% -- generated by encrypt-strings.py, DO NOT EDIT
# keystream: ks_block(j) = SHA-256( SALT || idx_be24 || byte(j) ), byte-wise XOR
# payload  : Base64( idx_be24 || cipher ); decrypt at runtime and intern()

.field private static final SALT_B64:Ljava/lang/String; = "%SALT%"
%FIELDS%
.field private static final CACHE:Ljava/util/concurrent/ConcurrentHashMap;


# direct methods
.method static constructor <clinit>()V
    .registers 2
%CLINIT_FILL%
    new-instance v0, Ljava/util/concurrent/ConcurrentHashMap;

    invoke-direct {v0}, Ljava/util/concurrent/ConcurrentHashMap;-><init>()V

    sput-object v0, Lcom/nc/strdec/StrDec;->CACHE:Ljava/util/concurrent/ConcurrentHashMap;

    return-void
.end method


.method public static d(Ljava/lang/String;)Ljava/lang/String;
    .registers 6

    sget-object v0, Lcom/nc/strdec/StrDec;->CACHE:Ljava/util/concurrent/ConcurrentHashMap;

    invoke-virtual {v0, p0}, Ljava/util/concurrent/ConcurrentHashMap;->get(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v1

    if-eqz v1, :cache_hit

    :try_start_dec
    invoke-static {p0}, Lcom/nc/strdec/StrDec;->dec(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v1
    :try_end_dec
    .catch Ljava/lang/Throwable; {:try_start_dec .. :try_end_dec} :catch_dec

    invoke-virtual {v0, p0, v1}, Ljava/util/concurrent/ConcurrentHashMap;->putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    if-eqz v2, :own_result

    check-cast v2, Ljava/lang/String;

    return-object v2

    :own_result
    return-object v1

    :catch_dec
    return-object p0

    :cache_hit
    check-cast v1, Ljava/lang/String;

    return-object v1
.end method


.method private static dec(Ljava/lang/String;)Ljava/lang/String;
    .registers 8

    const/4 v0, 0x2

    invoke-static {p0, v0}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v1

    const/4 v2, 0x0

    aget-byte v3, v1, v2

    and-int/lit16 v3, v3, 0xff

    shl-int/lit8 v3, v3, 0x10

    const/4 v4, 0x1

    aget-byte v5, v1, v4

    and-int/lit16 v5, v5, 0xff

    shl-int/lit8 v5, v5, 0x8

    or-int/2addr v3, v5

    const/4 v5, 0x2

    aget-byte v6, v1, v5

    and-int/lit16 v6, v6, 0xff

    or-int/2addr v3, v6

    invoke-static {v1, v3}, Lcom/nc/strdec/StrDec;->xor([BI)[B

    move-result-object v3

    new-instance v5, Ljava/lang/String;

    const-string v6, "UTF-8"

    invoke-direct {v5, v3, v6}, Ljava/lang/String;-><init>([BLjava/lang/String;)V

    invoke-virtual {v5}, Ljava/lang/String;->intern()Ljava/lang/String;

    move-result-object v5

    return-object v5
.end method


.method private static xor([BI)[B
    .registers 16

    array-length v0, p0

    add-int/lit8 v1, v0, -0x3

    new-array v2, v1, [B

    const-string v3, "SHA-256"

    invoke-static {v3}, Ljava/security/MessageDigest;->getInstance(Ljava/lang/String;)Ljava/security/MessageDigest;

    move-result-object v3

    sget-object v4, Lcom/nc/strdec/StrDec;->SALT_B64:Ljava/lang/String;

    const/4 v5, 0x2

    invoke-static {v4, v5}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v4

    const/4 v5, 0x0

    const/4 v6, 0x0

    :loop_outer
    if-ge v5, v1, :done

    invoke-virtual {v3, v4}, Ljava/security/MessageDigest;->update([B)V

    shr-int/lit8 v7, p1, 0x10

    int-to-byte v7, v7

    invoke-virtual {v3, v7}, Ljava/security/MessageDigest;->update(B)V

    shr-int/lit8 v8, p1, 0x8

    int-to-byte v8, v8

    invoke-virtual {v3, v8}, Ljava/security/MessageDigest;->update(B)V

    int-to-byte v9, p1

    invoke-virtual {v3, v9}, Ljava/security/MessageDigest;->update(B)V

    int-to-byte v10, v6

    invoke-virtual {v3, v10}, Ljava/security/MessageDigest;->update(B)V

    invoke-virtual {v3}, Ljava/security/MessageDigest;->digest()[B

    move-result-object v10

    const/4 v11, 0x0

    const/16 v12, 0x20

    :loop_inner
    if-ge v11, v12, :next_block

    if-ge v5, v1, :next_block

    add-int/lit8 v13, v5, 0x3

    aget-byte v14, p0, v13

    aget-byte v15, v10, v11

    xor-int v14, v14, v15

    int-to-byte v14, v14

    aput-byte v14, v2, v5

    add-int/lit8 v5, v5, 0x1

    add-int/lit8 v11, v11, 0x1

    goto :loop_inner

    :next_block
    add-int/lit8 v6, v6, 0x1

    goto :loop_outer

    :done
    return-object v2
.end method
'''

# ── smali 字符串字面量转义表(与 smali 汇编器的 unescape 对齐) ──────────
_UNESCAPE = {
    'n': '\n', 't': '\t', 'r': '\r', 'b': '\b', 'f': '\f',
    "'": "'", '"': '"', '\\': '\\',
}
_HEX = set('0123456789abcdefABCDEF')

# const-string 指令行:抓缩进 / jumbo / 目标寄存器 / 字面量起始
_INSTR_RE = re.compile(
    r'^(?P<indent>[ \t]*)const-string(?P<jumbo>/jumbo)?[ \t]+'
    r'(?P<dst>v\d+|p\d+)[ \t]*,[ \t]*"(?P<rest>.*)$')

# field 行携带的字符串字面量(R8 把 static final 常量折叠成 @value 注解形态)。
# 例: .field public static final URL:Ljava/lang/String; = "https://x"
# 类型必须以字段名后的 ':' 为锚(否则 [^;\s]+; 会把名字末尾的字符吞进类型)
_FIELD_RE = re.compile(
    r'^(?P<indent>[ \t]*)\.field(?P<mid>.*?)(?P<name>[A-Za-z_$][\w$]*):'
    r'(?P<type>[L\[][^\s]*?;)[ \t]*=[ \t]*"(?P<rest>.*)$')

# 值得加密的字段类型:String 本身,以及 String 数组(元素值同样是明文)
FIELD_STRING_TYPES = ('Ljava/lang/String;', '[Ljava/lang/String;')


def smali_unescape(text: str) -> str:
    """解码 smali 字符串字面量内容(两侧引号已剥掉)。

    识别不了转义时抛 ValueError(调用方跳过该条,绝不猜)——
    宁可漏一条也不静默改错字符串值。"""
    out = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if ch != '\\':
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= n:
            raise ValueError('结尾孤立反斜杠')
        esc = text[i]
        if esc == 'u':
            if i + 4 >= n:
                raise ValueError('\\u 转义不完整')
            hexs = text[i + 1:i + 5]
            if len(hexs) != 4 or any(c not in _HEX for c in hexs):
                raise ValueError('\\u 转义非 4 位十六进制')
            out.append(chr(int(hexs, 16)))
            i += 5
        elif esc in _UNESCAPE:
            out.append(_UNESCAPE[esc])
            i += 1
        else:
            raise ValueError(f'未知转义 \\{esc}')
    return ''.join(out)


def parse_const_string(line: str):
    """解析一条 const-string 指令行。
    返回 (match, literal_text, tail) 或 None(不是该指令/引号不闭合)。"""
    m = _INSTR_RE.match(line)
    if not m:
        return None
    rest = m.group('rest')
    i = 0
    while i < len(rest):
        c = rest[i]
        if c == '\\':
            i += 2
            continue
        if c == '"':
            break
        i += 1
    else:
        return None                                   # 引号不闭合,当异常行跳过
    return m, rest[:i], rest[i + 1:]


def parse_field_string(line: str):
    """解析携带字符串字面量的 .field 行(R8 折叠的 static final 常量)。
    返回 (match, literal_text, tail) 或 None。"""
    m = _FIELD_RE.match(line)
    if not m:
        return None
    if m.group('type') not in FIELD_STRING_TYPES:
        return None                                   # 只处理 String / String[] 字段
    rest = m.group('rest')
    i = 0
    while i < len(rest):
        c = rest[i]
        if c == '\\':
            i += 2
            continue
        if c == '"':
            break
        i += 1
    else:
        return None
    return m, rest[:i], rest[i + 1:]


def field_to_java_code(field_type: str, literal: str) -> str:
    """把字段字面量转成等价的 Java 源码字符串(用于转义)。"""
    return '"' + literal + '"'


def keystream(salt: bytes, idx: int, length: int) -> bytes:
    """与 stub xor() 逐字节一致的密钥流:块 j = SHA-256(salt || idx_be24 || j)。"""
    out = bytearray()
    j = 0
    idx_bytes = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    while len(out) < length:
        out += hashlib.sha256(salt + idx_bytes + bytes((j & 0xFF,))).digest()
        j += 1
    return bytes(out[:length])



    """与 stub xor() 逐字节一致的密钥流:块 j = SHA-256(salt || idx_be24 || j)。"""
    out = bytearray()
    j = 0
    idx_bytes = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    while len(out) < length:
        out += hashlib.sha256(salt + idx_bytes + bytes((j & 0xFF,))).digest()
        j += 1
    return bytes(out[:length])


def encrypt_payload(salt: bytes, idx: int, plain: bytes) -> str:
    """明文 → Base64( idx_be24 || cipher )。"""
    head = bytes(((idx >> 16) & 0xFF, (idx >> 8) & 0xFF, idx & 0xFF))
    ks = keystream(salt, idx, len(plain))
    cipher = bytes(p ^ k for p, k in zip(plain, ks))
    return base64.b64encode(head + cipher).decode('ascii')


def desc_to_dot(desc: str) -> str:
    """Lcom/x/Y; → com.x.Y"""
    return desc[1:-1].replace('/', '.')


def build_matchers(rules_path: str, classes_file):
    """规则文件 → (include 正则表, exclude 正则表)。语法与 dcc 侧完全一致。"""
    with open(rules_path, encoding='utf-8') as fp:
        raw_rules = [line.strip() for line in fp]

    includes, excludes = [], []
    activity_mode = False
    for rule in raw_rules:
        if not rule or rule.startswith('#'):
            continue
        negate = rule.startswith('!')
        body = rule[1:].strip() if negate else rule
        if not body:
            continue
        if body == 'activity*':
            activity_mode = True
            if not classes_file:
                raise SystemExit('❌ 规则含 activity*,必须提供 --classes 类列表文件')
            for cls in _RULES.expand_activity_keyword(classes_file):
                pat = _RULES.class_rule_to_filter(cls[1:-1], False)
                (excludes if negate else includes).append(re.compile(pat))
            continue
        pat = _RULES.class_rule_to_filter(body, _RULES.has_wildcard(body))
        (excludes if negate else includes).append(re.compile(pat))
    return includes, excludes, activity_mode


def parse_compiled_methods(path: str):
    """compiled_methods.txt → {(类名, 方法名, 原型)}(格式同 §4.2,无箭头)。"""
    result = set()
    with open(path, encoding='utf-8') as fp:
        for line in fp:
            line = line.strip()
            if not line:
                continue
            m = re.match(r'^(L[^;]+;)([^(]+)(\(.*\)\S+)$', line)
            if m:
                result.add((m.group(1), m.group(2), m.group(3)))
    return result


def iter_smali_files(decompiled_dir: str):
    for root, _dirs, files in os.walk(decompiled_dir):
        parts = root[len(decompiled_dir):].lstrip(os.sep).split(os.sep)
        if any(SMALI_DIR_RE.match(p) for p in parts if p):
            for f in files:
                if f.endswith('.smali'):
                    yield os.path.join(root, f)


def class_desc_of(content: str):
    """取 .class 行的类描述符(同 mark-native.py 的取法)。"""
    for line in content.split('\n'):
        if line.startswith('.class'):
            m = re.search(r'L[^;\s]+;', line)
            if m:
                return m.group(0)
    return None


STUB_DOT = STUB_DESC[1:-1].replace('/', '.')

# 已加密条目的形态:const-string 紧跟本桩的 invoke-static(用于续跑时续 idx)
_PAYLOAD_RE = re.compile(
    r'const-string(?:/jumbo)?[ \t]+(?:v\d+|p\d+)[ \t]*,[ \t]*"([^"\n]*)"\n'
    r'[ \t]*invoke-static \{[^}\n]*\}, ' + re.escape(STUB_DESC) + r'->d\(')


def is_system_class(cls_dot: str) -> bool:
    """系统类/框架依赖前缀判定(带点号前缀,不误伤 androidXxx 这种同前缀类)。"""
    return cls_dot.startswith(SYSTEM_CLASS_PREFIXES)


def classify(cls_dot: str, cls_desc: str, includes, excludes) -> str:
    """给类定性:no-match / system / excluded / stub / target。
    排除优先级最高(用户 ! 行 + 系统前缀 + 桩自身),再看 include。"""
    if not any(r.search(cls_desc) for r in includes):
        return 'no-match'
    if is_system_class(cls_dot):
        return 'system'
    if cls_dot == STUB_DOT:
        return 'stub'
    if any(r.search(cls_desc) for r in excludes):
        return 'excluded'
    return 'target'


def max_existing_idx(content: str) -> int:
    """已加密类里出现过的最大 idx(续跑时接着编号,避免 keystream 复用)。"""
    biggest = -1
    for m in _PAYLOAD_RE.finditer(content):
        try:
            raw = base64.b64decode(m.group(1), validate=True)
        except Exception:
            continue
        if len(raw) >= 3:
            biggest = max(biggest, int.from_bytes(raw[:3], 'big'))
    return biggest


def find_stub_path(decompiled_dir: str):
    """在 smali*/ 里找桩文件(只有解包目录下、且位于桩包路径中的才算)。"""
    for root, _dirs, files in os.walk(decompiled_dir):
        parts = root[len(decompiled_dir):].lstrip(os.sep).split(os.sep)
        if not any(SMALI_DIR_RE.match(p) for p in parts if p):
            continue
        if STUB_FILE in files and root.endswith(os.path.join(*STUB_PKG_DIR)):
            return os.path.join(root, STUB_FILE)
    return None


def read_existing_salt(decompiled_dir: str):
    """已存在且是本工具生成的桩 → 复用其 SALT_B64(否则旧密文解不开)。
    返回 (salt_bytes 或 None, 是否需要写桩)。同名非本工具文件 → fail-fast。"""
    stub_path = find_stub_path(decompiled_dir)
    if not stub_path:
        return None, True
    with open(stub_path, encoding='utf-8') as fp:
        content = fp.read()
    if STUB_GEN_MARK not in content:
        raise SystemExit(f'❌ 已存在同名类但非本工具生成,拒绝覆盖: {stub_path}\n'
                         f'   请改名或移走用户的 {STUB_DESC} 后重试')
    m = re.search(r'SALT_B64:Ljava/lang/String;[ \t]*=[ \t]*"([A-Za-z0-9+/=]+)"', content)
    if not m:
        raise SystemExit(f'❌ 桩文件缺少 SALT_B64,无法复用: {stub_path}')
    return base64.b64decode(m.group(1)), False


def _pick_smali_root(decompiled_dir: str) -> str:
    """桩落在哪个 smali 目录:优先 smali/,否则第一个 smali*/。"""
    preferred = os.path.join(decompiled_dir, 'smali')
    if os.path.isdir(preferred):
        return preferred
    for name in sorted(os.listdir(decompiled_dir)):
        if SMALI_DIR_RE.match(name) and os.path.isdir(os.path.join(decompiled_dir, name)):
            return os.path.join(decompiled_dir, name)
    raise SystemExit(f'❌ 解包目录下找不到 smali/ 或 smali_classes*/ : {decompiled_dir}')


def write_components_stamp(decompiled_dir: str, cls_desc: str) -> str:
    """记录本次注入的组件(类名 + 源文件路径)。

    报错十八教训:流水线中途会丢失信息(回编降级抹掉 dex 版本),必须在丢失前 save。
    这里同理 —— apktool 重打包会重新分派 dex 号,唯一稳定的定位依据是
    "描述符 + 源文件路径"对。落盘后,`clean` 子命令可长期正确清理残留的桩类
    (例如本次运行一条都没加密、旧桩却还在)。"""
    root = _pick_smali_root(decompiled_dir)
    payload = {
        'version': 1,
        'classes': [{
            'desc': cls_desc,
            'src': os.path.relpath(
                os.path.join(root, *STUB_PKG_DIR, STUB_FILE), decompiled_dir),
        }],
    }
    path = os.path.join(decompiled_dir, COMPONENTS_FILE)
    with open(path, 'w', encoding='utf-8') as fp:
        json.dump(payload, fp, ensure_ascii=False, indent=2)
        fp.write('\n')
    return path


def clean_components(decompiled_dir: str) -> int:
    """按组件标记删除残留的注入物(解密桩)。幂等,清完删标记文件。

    只删标记里登记的路径,且要求两者同时满足「路径在本解包目录内」+
    「文件内容带本工具生成标记」—— 绝不误删用户自己的类。"""
    path = os.path.join(decompiled_dir, COMPONENTS_FILE)
    if not os.path.isfile(path):
        return 0
    with open(path, encoding='utf-8') as fp:
        payload = json.load(fp)
    root_abs = os.path.abspath(decompiled_dir)
    removed = 0
    for entry in payload.get('classes', []):
        target = os.path.abspath(os.path.join(decompiled_dir, entry.get('src', '')))
        if not target.startswith(root_abs + os.sep):
            continue                                # 标记被篡改 → 绝不越界删除
        if not os.path.isfile(target):
            continue
        with open(target, encoding='utf-8') as fp:
            if STUB_GEN_MARK not in fp.read():
                continue                            # 不是我们的文件 → 不删
        os.remove(target)
        removed += 1
    os.remove(path)
    return removed


def write_stub(decompiled_dir: str, salt: bytes, stub_fields) -> str:
    """写解密桩。stub_fields: [(字段名, 密文 base64)] —— R8 折叠的 static final
    String 常量改成了对这些字段的引用,字段值由桩的 <clinit> 运行期解密填入。"""
    root = _pick_smali_root(decompiled_dir)
    stub_dir = os.path.join(root, *STUB_PKG_DIR)
    os.makedirs(stub_dir, exist_ok=True)
    stub_path = os.path.join(stub_dir, STUB_FILE)

    # 字段声明 + <clinit> 里的解密赋值
    field_decls = ''.join(
        f'\n.field public static final {name}:Ljava/lang/String;\n'
        f'.field private static final C_{name}:Ljava/lang/String; = "{payload}"\n'
        for name, payload in stub_fields)
    clinit_fill = ''.join(
        f'\n    sget-object v0, {STUB_DESC}->C_{name}:Ljava/lang/String;\n'
        f'\n    invoke-static {{v0}}, {STUB_DESC}'
        f'->d(Ljava/lang/String;)Ljava/lang/String;\n'
        f'\n    move-result-object v0\n'
        f'\n    sput-object v0, {STUB_DESC}->{name}:Ljava/lang/String;\n'
        for name, _payload in stub_fields)

    content = STUB_TEMPLATE.replace('%GEN_MARK%', STUB_GEN_MARK).replace(
        '%SALT%', base64.b64encode(salt).decode('ascii'))
    if stub_fields:
        content = content.replace('%FIELDS%', field_decls)
        content = content.replace('%CLINIT_FILL%', clinit_fill)
    else:
        content = content.replace('%FIELDS%', '')
        content = content.replace('%CLINIT_FILL%', '')
    with open(stub_path, 'w', encoding='utf-8') as fp:
        fp.write(content)
    return stub_path


def process_file(path: str, cls_desc: str, includes, excludes,
                 exclude_methods, salt: bytes, next_idx: int):
    """就地加密一个 .smali 文件。返回 (改动字符串数, 新 next_idx)。"""
    with open(path, encoding='utf-8') as fp:
        content = fp.read()
    if CLASS_MARK in content:
        # 幂等:整类已处理。但仍要把它用过的 idx 计入,续跑时不重复编号
        return 0, max(next_idx, max_existing_idx(content) + 1), []

    lines = content.split('\n')
    out = []
    cur_method = None
    hits = 0
    idx = next_idx
    stub_fields = []          # 需要生成的桩字段: [(字段名, 密文)]
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('.method'):
            # 同 mark-native.py:名字取括号前紧邻一段,防参数里嵌方法引用的贪婪误判
            m = re.match(r'\.method\s+(.*\S)\s*(\(.*\)\S+)\s*$', stripped)
            if m:
                toks = m.group(1).split()
                cur_method = (toks[-1], m.group(2))
            else:
                cur_method = None
            out.append(line)
            continue
        if stripped == '.end method':
            cur_method = None
            out.append(line)
            continue

        # R8 折叠的 static final String 常量: .field ... = "明文"
        # 改为引用解密桩的静态字段,桩的 <clinit> 运行期解密。
        # (这类字面量不在 const-string 指令里,必须单独处理)
        fparsed = parse_field_string(line)
        if fparsed and cur_method is None:
            fm, fliteral, ftail = fparsed
            try:
                fplain = smali_unescape(fliteral)
            except ValueError as exc:
                print(f'⚠️ 跳过无法安全解析的字段字面量({exc}): {path}', file=sys.stderr)
                out.append(line)
                continue
            if idx > IDX_MAX:
                raise SystemExit(f'❌ 加密字符串数超过 {IDX_MAX}(idx 3 字节上限),请缩小规则范围')
            field_name = f'F{idx:06d}'          # 用全局 idx 命名,跨类天然唯一
            stub_fields.append((field_name, encrypt_payload(salt, idx,
                                                            fplain.encode('utf-8'))))
            # 保留 .field 声明与修饰符,把初值换成桩字段引用
            out.append(f'{fm.group("indent")}.field{fm.group("mid")}'
                       f'{fm.group("name")}:{fm.group("type")} = '
                       f'{STUB_DESC}->{field_name}:{fm.group("type")}{ftail}')
            idx += 1
            hits += 1
            continue

        excluded_by_dex2c = bool(
            cur_method and (cls_desc, cur_method[0], cur_method[1]) in exclude_methods)

        # 已加密条目(解密桩可能来自上一次运行)→ 跳过,并续用序号,
        # 避免把密文当明文再加密一次
        if STUB_DESC + '->d(' in line:
            out.append(line)
            midx = max_existing_idx(line + '\n')
            if midx >= 0:
                idx = max(idx, midx + 1)
            continue

        parsed = parse_const_string(line)
        if not parsed:
            out.append(line)
            continue
        if excluded_by_dex2c:
            out.append(line)                            # 该方法将被 dex2c 抽走 → 不浪费体积
            continue

        m, literal, tail = parsed
        try:
            plain = smali_unescape(literal)
        except ValueError as exc:
            print(f'⚠️ 跳过无法安全解析的字符串({exc}): {path}', file=sys.stderr)
            out.append(line)
            continue

        if idx > IDX_MAX:
            raise SystemExit(f'❌ 加密字符串数超过 {IDX_MAX}(idx 3 字节上限),请缩小规则范围')

        payload = encrypt_payload(salt, idx, plain.encode('utf-8'))
        jumbo = m.group('jumbo') or ''
        indent = m.group('indent')
        dst = m.group('dst')
        out.append(f'{indent}const-string{jumbo} {dst}, "{payload}"{tail}')
        out.append(f'{indent}invoke-static {{{dst}}}, {STUB_DESC}'
                   f'->d(Ljava/lang/String;)Ljava/lang/String;')
        out.append(f'{indent}move-result-object {dst}')
        idx += 1
        hits += 1

    if hits == 0:
        return 0, next_idx, []

    # 插幂等标记注释(注释不进 dex)
    final = []
    marked = False
    for ln in out:
        final.append(ln)
        if not marked and ln.lstrip().startswith('.class'):
            final.append(f'{CLASS_MARK} (do not remove)')
            marked = True
    with open(path, 'w', encoding='utf-8') as fp:
        fp.write('\n'.join(final))
    return hits, idx, stub_fields


def main() -> int:
    argv = sys.argv[1:]
    # 子命令:clean(按组件标记清残留,幂等) | encrypt(默认)
    if argv and argv[0] == 'clean':
        if len(argv) != 2:
            print('用法: encrypt-strings.py clean <解包目录>', file=sys.stderr)
            return 1
        removed = clean_components(argv[1])
        print(f'✅ 清理残留解密桩: {removed} 个')
        return 0

    ap = argparse.ArgumentParser(
        description='dex 层字符串常量加密(按 dcc 同款规则选类,注入 Java 解密桩)')
    ap.add_argument('decompiled', help='apktool 解包目录(含 smali*/)')
    ap.add_argument('rules', help='类名规则文件(语法同 dex2c_rules)')
    ap.add_argument('--classes', help='activity* 展开所需类列表(make-filter-from-apk 产物)')
    ap.add_argument('--exclude-methods',
                    help='compiled_methods.txt:这些方法将被 dex2c 抽走,跳过不加密')
    ap.add_argument('--salt-hex', help='固定 salt(16 字节 hex),仅供测试/复现')
    ap.add_argument('--quiet', action='store_true', help='只打错误')
    args = ap.parse_args(argv)

    if not os.path.isdir(args.decompiled):
        print(f'❌ 解包目录不存在: {args.decompiled}', file=sys.stderr)
        return 1
    if not os.path.isfile(args.rules):
        print(f'❌ 规则文件不存在: {args.rules}', file=sys.stderr)
        return 1

    includes, excludes, activity_mode = build_matchers(args.rules, args.classes)
    if not includes:
        print('❌ 规则文件没有产生任何包含规则(只有排除/注释?)', file=sys.stderr)
        return 1

    exclude_methods = set()
    if args.exclude_methods:
        if not os.path.isfile(args.exclude_methods):
            print(f'❌ --exclude-methods 文件不存在: {args.exclude_methods}', file=sys.stderr)
            return 1
        exclude_methods = parse_compiled_methods(args.exclude_methods)

    if args.salt_hex:
        salt = bytes.fromhex(args.salt_hex)
        if len(salt) != 16:
            print('❌ --salt-hex 必须是 16 字节(32 位 hex)', file=sys.stderr)
            return 1
    else:
        salt = secrets.token_bytes(16)

    # 幂等/复用:已有桩则沿用其 salt(否则旧密文解不开)
    existing_salt, need_write_stub = read_existing_salt(args.decompiled)
    if existing_salt is not None:
        salt = existing_salt

    total_str, total_cls, idx = 0, 0, 0
    skipped_system = skipped_excluded = skipped_stub = 0
    all_stub_fields = []
    for path in sorted(iter_smali_files(args.decompiled)):
        with open(path, encoding='utf-8') as fp:
            content = fp.read()
        cls_desc = class_desc_of(content)
        if not cls_desc:
            continue
        cls_dot = desc_to_dot(cls_desc)
        verdict = classify(cls_dot, cls_desc, includes, excludes)
        if verdict == 'no-match':
            continue
        if verdict == 'system':
            skipped_system += 1
            continue
        if verdict == 'excluded':
            skipped_excluded += 1
            continue
        if verdict == 'stub':
            skipped_stub += 1
            continue
        n, idx, fields = process_file(path, cls_desc, includes, excludes,
                                     exclude_methods, salt, idx)
        if n:
            total_str += n
            total_cls += 1
            all_stub_fields.extend(fields)

    if need_write_stub and total_str > 0:
        stub_path = write_stub(args.decompiled, salt, all_stub_fields)
        stamp = write_components_stamp(args.decompiled, STUB_DESC)
        if not args.quiet:
            print(f'  🔧 注入解密桩: {os.path.relpath(stub_path, args.decompiled)}'
                  f' (组件标记 {os.path.basename(stamp)}'
                  f'{f", 字段常量 {len(all_stub_fields)} 个" if all_stub_fields else ""})')
    # need_write_stub 但一条都没加密 → 不注入桩(不给产物塞无用类,且省掉 dex 内新类)

    if not args.quiet:
        if activity_mode:
            print('ℹ️ 规则含 activity*,已按 --classes 展开')
        if skipped_system:
            print(f'ℹ️ 命中规则但被硬排除(系统/框架依赖类)跳过: {skipped_system} 个类')
        if skipped_excluded:
            print(f'ℹ️ 被用户 ! 规则排除跳过: {skipped_excluded} 个类')
        if skipped_stub:
            print(f'ℹ️ 解密桩自身跳过: {skipped_stub} 个')
        print(f'✅ 字符串加密完成: {total_str} 条 / {total_cls} 个类'
              f' (salt={base64.b64encode(salt).decode("ascii")[:8]}..., '
              f'桩={"已注入" if (need_write_stub and total_str) else "复用/未用"})')
        if total_str == 0:
            print('⚠️ 没有任何字符串被加密 —— 检查规则是否命中(系统/依赖类会被硬排除)',
                  file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
